### PR TITLE
install 'yq' on Travis-CI

### PR DESCRIPTION
**Pull request by xcoulon**
Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by xcoulon** [comment]
PR to fix https://travis-ci.org/codeready-toolchain/toolchain-operator/builds/646749750

**Comment by MatousJobanek** [comment]
hmm... it should not fail actually as there is nothing that should be enriched... 
The script should be improved too to check for the existence of the `yq` command only in the cases when it's really needed - I will do it

**Comment by MatousJobanek** [comment]
here is the fix for the scripts: https://github.com/codeready-toolchain/api/pull/99

**Comment by xcoulon** [comment]
> hmm... it should not fail actually as there is nothing that should be enriched...
> The script should be improved too to check for the existence of the `yq` command only in the cases when it's really needed - I will do it

ah right, so I guess we could close this PR then?

**Comment by MatousJobanek** [comment]
yeah, it's not needed - I already reran the job and it passed: https://travis-ci.org/codeready-toolchain/toolchain-operator/builds/646749750

**Comment by xcoulon** [comment]
> yeah, it's not needed - I already reran the job and it passed: https://travis-ci.org/codeready-toolchain/toolchain-operator/builds/646749750

ok, so let me close this one now, then.

**Pull request closed without merging**
