### PR TITLE
Update operator-sdk to 0.16.0

### PR DESCRIPTION
**Pull request by alexeykazakov**

### CODE REVIEW

**Comment by MatousJobanek** [comment]
@alexeykazakov could you please change it also in the README here? https://github.com/codeready-toolchain/toolchain-operator/blob/master/README.adoc#prerequisites

**Comment by alexeykazakov** [comment]
> could you please change it also in the README here?

Good catch. Fixed.

**Comment by MatousJobanek** [comment]
Thanks :+1:

**Pull request merged**
